### DISCUSSION TITLE
Courriel de confirmation

### DISCUSSION THREAD

**Discussion by maxpouliot** [MTESSDev/FRW#12] [Annonces]
Allo, 

dans la dernière démonstration, à la fin du formulaire, un pop-up apparaissait et demandait le courriel du client afin de lui envoyer une confirmation. Est-ce que ce popup est systématique ou bien il est possible de ne pas l'afficher? 

Merci!

**Comment by j0ber** [comment]
Oui c'est possible. Pour ne pas avoir cette modale, il suffit de mettre dans le bloc config :  

```yaml
confirmationTransmission:
    modaleCourrielConfirmation:
      actif: false
```

Notez qu'il est aussi possible de ne pas avoir cette modale en spécifiant un champ courriel  présent dans le formulaire. L'adresse courriel utilisée pour le courriel de confirmation sera alors la valeur du champ courriel spécifié. Vous pouvez le faire en spécifiant le bloc config : 

```yaml
confirmationTransmission:
    modaleCourrielConfirmation:
       nomChampCourrielUtilisateur: NomDuChampCourrielUtilisateurDansModele
```
