### DISCUSSION TITLE
Limiter les choix d'une liste dérouranle

### DISCUSSION THREAD

**Discussion by maxpouliot** [MTESSDev/FRW#13] [Annonces]
Bonjour, 

est ce que la solution permet de limiter le contenu d'une liste déroulante en fonction d'un choix fait au préalable? Par exemple, si je réponds oui, le champ X à les choix 1,2 ou 3 et si je répond non, le même champ X à les choix 4 et 5

Merci!

**Comment by j0ber** [comment]
Pour le moment non.

C'est en cours de développement. Voir https://github.com/MTESSDev/FRW/issues/19.

**Comment by anisite** [comment]
Ce n'est pas possible tel que mentionné, par contre, tous nos formulaires actuels ont ce principe quand même avec une solution de contournement. Il est possible de mettre deux fois le même `name` de champ dans la config, mais de changer la liste des valeurs, il suffit ensuite d'appliquer un `v-if` différent et mutuellement explicite, ce qui fait qu'une seule des deux instances sera afichée à la fois et vous pourrez donc reproduire le comportement désiré en attendant.

comme par exemple (ici champ NAS obligatoire juste dans un cas précis, mais des radios ou des checkbox au lieu d'un champ texte ferait la même chose) :
```yaml
- name: Nas
  v-if: val('TypeDemande').includes('AideEmploi')
  type: nas
  outerClasses: md
  label:
    fr: Numéro d'assurance sociale
    en: Social insurance number
- name: Nas
  v-if: "!val('TypeDemande').includes('AideEmploi')"
  type: nas
  outerClasses: md
  label:
    fr: Numéro d'assurance sociale
    en: Social insurance number
  validations:
    optional: null
```
