### DISCUSSION TITLE
Validation personnalisée dans champs de texte de groupe répétable

### DISCUSSION THREAD

**Discussion by ageliinas** [MTESSDev/FRW#130] [Annonces]
Bonjour!
Pour l'un de nos formulaire, on aimerait pouvoir utilisé la fonction de groupe répétable, car on veut permettre au gens de pouvoir ajouter et supprimer des périodes. Dans ce groupe, il y a deux champs textes pour l'inscription d'année. Par contre, nous devons inclure une validation entre les différentes périodes pour être en mesure d'empêcher les utilisateurs de réinscrire la même année déjà inscrite dans une période (voir les deux champs textes en rouge dans l'image jointe). Est-ce possible, et si oui, comment selon vous?

Merci :)

![1](https://github.com/MTESSDev/FRW/assets/80847091/7430f2b9-938b-4dea-92df-85cb75e5edb3)

**Comment by j0ber** [comment]
Bonjour,

Tout d'abord vous aurez besoin d'un validation personnalisée, voir ici : https://formulaires.it.mtess.gouv.qc.ca/fr/Form/7/P700U/0/N/#p=validationsCustom.

Le concept est bien expliqué, cependant dans votre cas c'est encore plus complexe, car vous ne pouvez pas passer des valeurs en paramètre à la méthode de validation. 

La méthode de validation devra obtenir la plage des années couvertes par les différentes valeurs saisies dans les groupes et vérifier que la valeur saisie n'y figure qu'une seule fois (car le validateur n'a aucune idée de l'occurrence de groupe qu'il valide).

C'est un cas très intéressant et complexe.

Je devrai l'explorer et en ajouter un exemple dans notre guide de configuration. 

Pouvez-vous inclure votre bloc de configuration pour ce groupe répétable s.v.p. ?  Je vais utiliser cet exemple tel quel.

Je devrais pouvoir regarder ça au cours des prochains jours.

Je vous reviens!

**Reply by ageliinas** [reply]
Bonjour,

Voici le code actuel du groupe répétable:

```
- type: repeatableGroup
              name: anneesRachat
              repeatable: true
              limit: 5
              label: 
                fr: Veuillez inscrire l’année correspondant à chaque période concernée par votre demande. Si une de ces périodes s’étend sur plus d’une année, veuillez inscrire toutes les années touchées.
              help:
                  fr: Par exemple, si votre demande concerne une période allant de novembre 2015 à juin 2016, vous devez inscrire « 2015-2016 ». 
              instanceLabel:
                fr: Période 
              addLabel:
                fr: Ajouter une période 
              removeLabel:
                fr: Supprimer cette période
              validations:
                optional: null          
              components: 
                  - type: inline
                    components:                   
                    - type: text
                      name: debutAnnee
                      label:
                        fr: Année de début de la période
                      outerClasses: md
                      placeholder:
                        fr: 'exemple 2022'
                      validations:
                        min: 4,length
                        max: 4,length    
                        number:     
                    - type: text
                      name: finAnnee
                      label:
                        fr: Année de fin de la période
                      placeholder:
                        fr: 'exemple 2023'
                      outerClasses: md
                      validations:
                        min: 4,length
                        max: 4,length    
                        number: 
``` 

Merci! :)
