### DISCUSSION TITLE
Appel soumission formulaire et secret à l'appel de l'API

### DISCUSSION THREAD

**Discussion by PhilippeLRETQC** [MTESSDev/FRW#136] [Annonces]
Bonjour,

Lors de la soumission d'un formulaire après les différents traitements MESS. Il y a l'appel à l'API du système autorisé. Nous allons mettre en place le secret (API Key) pour cet appel. Le secret du système autorisé doit vous être envoyé comment pour les différents environnements?

Il sera bien mis dans le header? Si oui, il est possible de spécifier le nom du champ.

Merci beaucoup,
Philippe

**Comment by loima02** [comment]
Bonjour!

La transmission du formulaire est lancée à même FRW via votre fichier de configuration de transmission. L'API key n'a pas besoin d'être passée en paramètres.

**Comment by anisite** [comment]
Bonjour,

Juste pour précision, si vous passez un objet `form` pour le préremplissage et que vous avez (supposons) un autre objet nommé `secure` ou tout autre nom à côté qui contiendrait par exemple `jeton` avec une valeur comme `MXzpzdtxbXPsSjBaMgxIWkxVdVtGxueD`, il est très simple alors de changer la configuration dans le fichier transmission.v0.yml pour y ajouter n'importe quel nom de header dans le bloc header tel que démontré plus bas avec l'exemple `Authorization` ou `enteteCustom`.

````yaml
# La liste des clients http
http_client:
  # Nom de votre client, ici appel_externe
  appel_externe:
    # Méthode d'appel de votre API, Peut-être POST, PUT, PATCH ou autre... normalement POST est le meilleur choix
    method: POST
    # Url de votre API, des paramètres en GET ici peuvent être passés, il est possible de mettre des variables aussi
    url: http://votreapi.ministere.gouv.qc.ca/api/endpoint
    # Tous les headers que votre API doit reçevoir sont ici, possible aussi de mettre des variables
    headers:
      Accept: application/json
      Authorization: Bearer {{{ DonneesFormulaire.secure.jeton }}} 
      enteteCustom: {{{ DonneesFormulaire.form.champXYZ }}} 
    content:
      # Ici le json_content que nous allons passés à votre API, vous êtes libres de mettre la structure que vous voulez, {{{Json .}}} permet de tout "dumper" les variables de l'application vers votre API (voir Variables ci-dessous), utile aussi pour connaître les variables/objets disponibles
      json_content: |
          {{{Json .}}}
[... le reste de votre config...]
````

N'hésitez pas s'il y a quoi que ce soit.
