### DISCUSSION TITLE
URL de redirection pour la version anglaise

### DISCUSSION THREAD

**Discussion by ageliinas** [MTESSDev/FRW#145] [Annonces]
Bonjour,

Selon nos validations, nous envoyons le client vers une page web en utilisant 'redirectionURL' quand il ne répond pas aux critères. Il n'y a pas de problème quand c'est seulement une url. Cependant, si nous avons un client qui a sélectionné sur le web l'anglais, nous devons pouvoir envoyer vers la page web anglaise.

Nous avons essayé ceci:
```
config:
  aiguillage:
    choix:
      # Possibilité de pointé à un formulaire précis selon la condition.
      - vif: val('Section_Demandepourvous') === 'off' || val('SectionGuide_Rachat') === 'on' 
        mode: redirectionUrl
        url: 
          fr: https://www.retraitequebec.gouv.qc.ca/fr/formulaires/deconnexion/Pages/deconnexion.aspx
          en: https://www.retraitequebec.gouv.qc.ca/en/formulaires/deconnexion/Pages/deconnexion.aspx
``` 
Mais cela cause un problème technique et ne fonctionne pas. Avez-vous une solution?

Merci,
Bonne journée!
