### DISCUSSION TITLE
Lien avec une partie dynamique

### DISCUSSION THREAD

**Discussion by PhilippeLRETQC** [MTESSDev/FRW#157] [Annonces]
Bonjour,

Il y a moyen de mettre une partie variable dans un lien dont on utiliserait une variable dans le formulaire? Nous voulons faire une navigation vers le "nous joindre" personnalisé que nous avons avec du contexte.

L'objectif serait de mettre le lien dans le fichier defaut et on remplace uniquement la variable dans les formulaires pour éviter de copie le lien partout.

````yaml
  piv:
    nousJoindre:
      actif: true
      texte:
        fr: Nous joindre
        en: Contact us
      urlLien: 
        fr: https://test.test?codeservice=TEST&codecategorie=CAT&pageappelant={{val('codeformulaire')}}
        en: https://test.test?codeservice=TEST&codecategorie=CAT&pageappelant={{val('codeformulaire')}}
````
