### DISCUSSION TITLE
Envoyer un courriel à l'adresse saisie dans le formulaire

### DISCUSSION THREAD

**Discussion by jpbeaulieu1** [MTESSDev/FRW#246] [Annonces]
Bonjour
J'utilise la configuration "envoyerCourriel" décrite ici:
https://github.com/MTESSDev/FRW/blob/main/Documentation/fichiers-transmission.md

Quand j'utilise une adresse dans la config, il n'y a pas d'erreur
```
gabaritsCourriels:
  - id: confirmation
    # Liste des destinataires (peut être une liste)
    a:
      tous: 
        - 'esun-a02@essais.mess.gouv.qc.ca'
 ```
  Je voudrais envoyer le courriel à une adresse saisie dans le formulaire. J'ai essayer cette syntaxe mais j'ai l'erreur plus bas
 ```
 gabaritsCourriels:
  - id: confirmation
    # Liste des destinataires (peut être une liste)
    a:
      tous: 
        - '{{donneesFormulaire.form.courrielDestination}}'
   ```
  "Message": "La liste de destinataires contient un ou plusieurs adresses invalides. Veuillez les corriger afin de continuer.",
 
Quel est la bonne configuration? Et si L'adresse était dans un groupe et que je veux prendre l'adresse du premier élément du groupe?

Merci

**Comment by LarcM7** [comment]
reliée à #197 
tri en cours

**Comment by jpbeaulieu1** [comment]
J'obtiens cette erreur maintenant:
Le paramètre 'A:' est absent de votre gabarit de courriel dans la config de transmission. Erreur

```
etapes:
  # Traiter les documents transmis par les utilisateurs dans votre formulaire
  - tache: traiterDocumentsSoumis
        
  # Générer un document style questions/réponses à partir d'un gabarit word (gabarit par défaut)
  - tache: genererWord
  # Ajouter estampille, permet d'ajouter une "Étampe" sur un document 
    # comme pour l'officialiser (mettre la date de transmission, 
    # le no. de confirmation, etc)
  - tache: ajouterEstampille
  - tache: envoyerCourriel
    options:
      gabarit: confirmation
      filtresDocuments:
        - typeFiltre: tacheSource
          valeurs: genererWord
  - tache: appelerServiceExterne
    options:
      client: appel_externe
      # Permet d'indiquer de ne pas effectuer l'appel reel en mode test
      #modeBoutonTesterTransmission: simuler

gabaritsCourriels:
  - id: confirmation
    # Liste des destinataires (peut être une liste)
    production: 
      - '{{donneesFormulaire.form.CourrielDestinataire}}'
    # Nom de l'expéditeur (Par défaut, "Formulaires en ligne" ou "Online forms" selon la langue)
    nomExpediteur: Formulaires en ligne - RBQ
    # L'objet du courriel peut contenir des parties variables
    objet: 'Confirmation de transmission - {{donneesFormulaire.form.title}}'
    # Les données du formulaires peuvent être réutilisées dans le contenu du courriel
    corps: |
      <p>Bonjour {{donneesFormulaire.form.informationDemandeur.prenom}} {{donneesFormulaire.form.informationDemandeur.nom}},</p>
      <p>Nous vous confirmons la transmission de votre {{donneesFormulaire.form.title}}.</p>
      <p>Votre numéro de confirmation est le : <b>{{donneesFormulaire.X-NoConfirmation}}</b></p>
        # Pour faire afficher les documents téléchargeables, il faut ajouter le tableau ci-dessous. Une liste contenant chaque document avec son nom original dans FRW sera ajoutée au contenu du courriel. Sur le clique du lien, le document sera téléchargé.
        <ul>
          {{#listePJ}}
        <li><a href="{{url}}">{{nomOriginal}}</a></li>
          {{/listePJ}}
        </ul>
```

**Reply by Hutson48** [reply]
Bonjour,
Nous allons ajuster la documentation dans le Github. D'où vient votre exemple?
Bonne journée,

**Reply by LarcM7** [reply]
Salut Jean-Pierre,

Je pense qu'il te manque juste le palier "a:" dans la config gabaritsCourriels juste au-dessus de "production:".

voir exemple dans la doc : https://github.com/MTESSDev/FRW/blob/main/Documentation/fichiers-transmission.md#exemple-de-toutes-les-possibilit%C3%A9es-de-configuration

````
# Liste des gabarits de courriel pour la tâche "envoyerCourriel"
gabaritsCourriels:
  - id: confirmation
    # Liste des destinataires (peut être une liste)
    a:
      tous: 
        - 'esun-a02@essais.mess.gouv.qc.ca'
````

J'espère que ça va t'aider.

Bonne journée
