### DISCUSSION TITLE
utiliser courrielExpediteur et champs du formulaire dans courrielProchainUtilisateur

### DISCUSSION THREAD

**Discussion by jpbeaulieu1** [MTESSDev/FRW#252] [Annonces]
Bonjour
Actuellement la config courrielExpediteur n'est pas prise en compte dans la config courrielProchainUtilisateur. Ce pourrait être utile. Aussi, l'utilisation de champs du formulaire ne semble pas prise en compte dans le corps

```
  courrielProchainUtilisateur:
    nomExpediteur: Formulaires en ligne - RBQ
    courrielExpediteur: "NEPASREPONDRE@unMO.gouv.qc.ca"
    objet: 'Démarrage du formulaire : {0}'
    corps: |
        <p>Bonjour {{donneesFormulaire.form.informationDemandeur.prenom}}</p>
        <p>Cliquez ici pour démarrer le formulaire : <a href="{0}">Démarrer</a></p>
```
![image](https://github.com/MTESSDev/FRW/assets/112179879/d3cc60a5-0fc7-4df0-be91-13d413be35da)
