### DISCUSSION TITLE
Placement d'un champ

### DISCUSSION THREAD

**Discussion by ChrisThe01** [MTESSDev/FRW#265] [Annonces]
Bonjour,

Est-ce qu'il est possible de mettre un champ à la droite dans le formulaire ?

Merci,

**Comment by j0ber** [comment]
Bonjour,

À droite complètement non. À droite d'un autre champ complémentaire oui.

Tel que stipulé dans les règles de design Québec.ca : 
_Dans le format bureau et le format tablette, deux champs peuvent être placés côte à côte seulement s’ils sont complémentaires_

https://design.quebec.ca/design/composants/formulaire/champ-texte

Ci-dessous un exemple de configuration dans un formulaire :


```
- type: inline
   components:
     - name: Telephone
        type: tel
        label:
          fr: Téléphone
     - name: Poste
        type: text
        outerClasses: md
        label:
          fr: Poste
        validations:
          optional: null
```
