### DISCUSSION TITLE
Comment éviter que les champs "Confirm" sont transmis?

### DISCUSSION THREAD

**Discussion by jpbeaulieu1** [MTESSDev/FRW#271] [Annonces]
Bonjour

J'utilise 

```
- name: MDPConfirmation
  type: password
  label: 
    fr: Mot de passe (confirmation)
    en: (EN)Confirmer le mot de passe
  validations:
    confirm: MDPAConfirmer
```

Dans les données transmise, je ne vois pas le champ "MDPAConfirmer" ce qui est correct. Mais je vois quand même le champ "MDPConfirmation"

```
"form": {
        "validAll": true,
        "EtatRevision": "sans-erreur",
        "PjManquantes": [],
        "courrielValide": "true",
        "categorieExamen": "REIBH",
        "typeDemande": "initiale",
        "informationDemandeur": [
          {
            "courriel": "test@rbq.gouv.qc.ca",
            "courrielConfirmation": "test@rbq.gouv.qc.ca"
          }
        ],
        "courrielDestination": "test@rbq.gouv.qc.ca",
        "MDPConfirmation": "Test4"
      }
```
est-ce qu'il y a une façon pour éviter que les champs `validations: confirm:` ne soit pas transmis? Ou au moins les champs `type: password` parce que le confirm des courriel c'est moins grave.
