### DISCUSSION TITLE
Aiguillage différé vers un formulaire, via un courriel de reprise - Données non modifiable?

### DISCUSSION THREAD

**Discussion by jpbeaulieu1** [MTESSDev/FRW#272] [Annonces]
Bonjour

Nous utilisons la fonctionnalité d'aiguillage pour forcer les utilisateurs à valider leur adresses courriel.   Nous demandons quel formulaire ils veulent compléter et nous leur demandons le courriel et le mot de passe pour que l'aiguillage les envoie sur le bon formulaire. Ça  fonctionne bien. L'adresse courriel est aussi bien préremplie dans le formulaire 2 puis que le groupe et le champs porte le même nom. Par contre nous constatons est que peu importe les autres champs présents dans le groupe portant le même nom dans le formulaire 2, nous ne recevons que les données du formulaire 1. Nous nous attendions à recevoir toutes les données du formulaire 2. Est-ce que nous utilisons la fonctionnalité correctement?

J'ai ce groupe dans mon formulaire 1:
```
 - type: group
   name: informationDemandeur
   components:
   - name: courriel
     type: email
     label:
       fr: Courriel
       en: Email address
     help :
       fr: Un message de validation vous sera envoyé à cette adresse courriel. Veuillez verifier vos indésirables si vous n'avez rien reçu.
       en: (eng) Un message de validation vous sera envoyé à cette adresse courriel. Veuillez verifier vos indésirables si vous n'avez rien reçu.
   - name: courrielConfirmation
     type: email
     label:
       fr: Courriel (confirmation)
       en: Email address (confirmation)
     validations:
       confirm: courriel
   - type: password
            name: MDPAConfirmer
            label: 
                fr: Mot de passe
                en: (EN)Confirmer le mot de passe
          - type: password
```
Dans le formulaire 2, j'ai le même groupe mais avec d'autres champs en plus du courriel
```
- type: group
  name: informationDemandeur
  components:
  - name: salutation
    type: radio
    label:
      fr: Salutation
      en: (eng) Salutation
    options:
      Mr.:
        fr: Monsieur
        en: (eng) Monsieur
      Mrs.:
        fr: Madame
        en: (eng) Madame

  - name: nom
    type: text
    label:
      fr: Nom
      en: Name
  - name: prenom
    type: text
    label:
      fr: Prénom
      en: First name
  - name: dateNaissance
    type: date
    label:
      fr: Date de naissance
      en: Date of birth
    validations:
      before:
  - name: courriel
     type: email
     label:
       fr: Courriel
       en: Email address
     additionals:
       :disabled: true
```

Dans les outil de Dev en IT, je vois bien les données
```
"form": {
          {
            "salutation": "Mr.",
            "nom": "INC.",
            "prenom": "FERME",
            "telephone": "418 999-9999",
            "courriel": "test@rbq.gouv.qc.ca",
            "dateNaissance": "2024-05-28",
        }
}
```
Mais les données envoyé sont seulement celle du formulaire 1
```
"donneesFormulaire": {
      "form": {
        "informationDemandeur": [
          {
            "courriel": "test@rbq.gouv.qc.ca",
            "courrielConfirmation": "test@rbq.gouv.qc.ca",
          }
        ],
      },
      "systeme": {},
      "formProtege": {
        "validAll": true,
        "EtatRevision": "sans-erreur",
        "PjManquantes": [],
        "informationDemandeur": [
          {
            "courriel": "test@rbq.gouv.qc.ca",
            "courrielConfirmation": "test@rbq.gouv.qc.ca",
          }
        ],
        "courrielDestination": "jean-pierre.beaulieu-ext@rbq.gouv.qc.ca",
        "MDPConfirmation": "Test4"
      },
      "config": {
        "domaines": {}
      },
      "X-NoConfirmation": 9999999999311,
      "X-DateTransmission": "2024-06-20T13:26:03.3722948-04:00"
```

Normalement, je devrais recevoir les données complètes du 2e formulaires

**Comment by LarcM7** [comment]
Salut Jean-Pierre, 

La raison de ce comportement est que ton groupe "informationDemandeur" est protégé dans le formulaire 2. 

Donc à la soumission, il reprend ses valeurs initiales du formulaire 1.

Ceci est by design car il nous était demandé de nous assurer que les valeurs remplies dans le formulaire 1 ne puissent pas être écrasées par la 2e personne dans le formulaire 2.

Est-ce qu'il serait possible pour toi de mettre les valeurs "en extra" du formulaire 2 dans un groupe qui possède un nom différent que _informationDemandeur_?

De cette façon les valeurs ne seraient pas protégées (donc réinitialisées) à la soumission du formulaire.

Je vais bonifier le P700 [section aiguillage](https://formulaires.it.mtess.gouv.qc.ca/fr/Form/7/P700U/0/N/#p=aiguillage) et ajouter une note qui explique la protection des données du formulaire 1 dans le formulaire 2.

J'espère que ça répond bien à ton problème.

Merci et bon vendredi.

**Comment by jpbeaulieu1** [comment]
Bonjour,

Je comprends.

Je peux mettre les données du formulaire 1 dans un groupe différent. Par contre ça ajoute un section en plus dans le formulaire 2 ce qui nous oblige à refaire le mapping des données pour récupérer le courriel.  Est-ce que je peux récupérer la valeur du courriel dans "formProtege" et la copier dans le champ du formulaire 2? Notre objectif est de toujours avoirs toutes les "informationDemandeur" complète dans le même objet pour tous les formulaires de façon à généraliser le mapping des données. 

Merci

**Reply by LarcM7** [reply]
Salut! 

Dany m'a donné la solution 😊😊😊

Tu peux récupérer la valeur dans le form en rajoutant **additionals: > :value:** ... avec la syntaxe suivante : 
```
            - type: text
              name: tonChampDuFormulaire2
              label:
                fr: Le champ dans lequel tu veux attribuer une valeur provenant du form
              additionals:
                :value: val('leNomDuChampDansLeFormQuiContientLaValeurQueTuVeux')
```

Moi ça fonctionne de mon côté pour un champ seul, regarde voir si ça fonctionne aussi dans un groupe comme dans ton cas?

J'espère que ça répondra à ton besoin.
