### DISCUSSION TITLE
Permettre de paramétrer la langue dans courrielProchainUtilisateur

### DISCUSSION THREAD

**Discussion by jpbeaulieu1** [MTESSDev/FRW#290] [Annonces]
Bonjour

Est-ce que ce serait possible d'avoir une configuration du genre?

```
courrielProchainUtilisateur:
    nomExpediteur: Formulaires en ligne - RBQ
    courrielExpediteur: "NEPASREPONDRE@unMO.gouv.qc.ca"
    objet: 
       fr: 'Démarrage du formulaire : {0}'
       en: 'Begin form : {0}'
    corps: 
       fr: Quelque chose
       en: Something
```

Actuellement, nous pouvons mettre le texte en français et en anglais dans le corps du courriel
