### DISCUSSION TITLE
Help pour un champ de type group

### DISCUSSION THREAD

**Discussion by ChrisThe01** [MTESSDev/FRW#326] [Annonces]
Bonjour,

Je voudrais mettre un help pour  un champ de type groupe. Par exemple :
````yaml
name: Methodologie
type: group
label:
  fr: Démarche de projet
help : Mon aide
````
Mais ça ne fonctionne pas. Le help se retrouve avant le group. Comme faire ? (Vois imprime-écran)
![image](https://github.com/user-attachments/assets/18141a81-feab-4dbe-9ba5-ff2515c58fe0)
