### DISCUSSION TITLE
ignorer champ dans document

### DISCUSSION THREAD

**Discussion by MJMESS** [MTESSDev/FRW#36] [Annonces]
Bonjour, je veux ignorer les champs hidden lors de la génération du document. 
J'ai trouvé ceci comme information et je l'ai essayé mais ça ne fonctionne pas, les champs sont toujours présent :
![image](https://user-images.githubusercontent.com/122536311/227598598-f230805f-199f-4828-a28f-7270f6c026fd.png)

Est-ce qu'il manque des indentations dans l'exemple ? Est-ce que champ1 doit être plutôt [champ1]

Merci à l'avance!

**Comment by vinnyboii** [comment]
Bonjour,
La valeur champ1 doit être remplacée par le nom du champ tel que vous l'avez défini dans votre configuration de formulaire.
Par exemple, j'ai ce champ dans ma configuration "form":
````yaml
components:
  - name: NomFamille
    type: text
    outerClasses: xl
    label: 
      fr: Nom de famille
      en: Last name
````
Si je veux ignorer ce champ dans la production du fichier, ma section dans le bind doit être:
````yaml
  ignorer:
   - champ: NomFamille
````
**J'ai ajusté la documentation, svp me revenir si c'est plus clair maintenant.

**Reply by MJMESS** [reply]
Bonjour, je n'avais pas mis champ1 c'était seulement pour expliquer avec votre exemple. :) J'avais bien mis le nom de mes champs. Mais ça ne fonctionne pas. 

Cependant, je viens de voir que dans le courriel que j'ai reçu il y a des indentations contrairement à la documentation. Je vais essayé la semaine prochaine.

Merci beaucoup!

**Comment by anisite** [comment]
Bonjour, il semble qu'il y avait une petite erreur d'indentation dans l'exemple, je viens de corriger, ignorer doit être sous templates au même niveau que "id", "name" et autres

````yaml
templates:
- id: template1
  name: Fichier word
  #ignorer permet de spécifier les champs du formulaire Web qu'on ne veut pas afficher dans le document produit.
  ignorer:
  #La valeur champ1 ou champ2 doit correspondre au nom du champ (name) que vous voulez exclure dans votre formulaire.
  - champ: TypesRevenusEmploi
  - champ: RevenuEmploiSalaireNet
````

Un schéma est en cours de fabrication pour vous aider dans vos saisies de binding.
