### ISSUE TITLE
Pouvoir réutiliser des éléments communs dans plusieurs formulaires

### ISSUE THREAD

**Issue by LarcM7** [MTESSDev/FRW#127]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Il est irritant lorsque j'ai des éléments communs à plusieurs formulaires de mon organisation et que je dois dupliquer les configurations de ces éléments dans plusieurs formulaires différents. Si une mise à jour d'un de ces éléments est nécessaire, il faut la faire à plusieurs endroits ce qui n'est pas optimal et augmente le risque d'erreur.

**Décrivez votre besoin**
J'aimerais pouvoir réutiliser des éléments (sections complètes, contrôles personnalisés ou autres) simplement, facilement et rapidement dans plusieurs formulaires sans avoir à dupliquer ces éléments.

**Décrivez les alternatives que vous avez envisagées**
Dupliquer les éléments.

**Proposition de solution**
Peut-être pouvoir faire référence à des éléments contenus dans un "fichier externe" (par exemple au niveau du système autorisé) dans un fichier de configuration d'un formulaire.

AB#61085

[AB#73325](https://devops700.itp.extra/700/TPM/_workitems/edit/73325)

**Comment by jpbeaulieu1** [comment]
Bonjour
Nous avons le même besoin
Merci

**Comment by Ghost3044** [comment]
Bonjour,

Nous réaliserons une POC cette année pour étudier comment intégrer cette fonctionnalité dans FRW. Nous vous tiendrons informés dès que nous l'aurons priorisée.

Bonne journée.

**Comment by jpbeaulieu1** [comment]
Est-ce qu'il sera possible de passer des paramètres au section réutilisable? Par exemple pour faire afficher une question à l'intérieur de la section réutilisable selon la réponse à une autre qui n'est pas dedans. On aurait aussi la possibilité de passer un paramètre par défaut.

du genre
```
- type: radio
  name: questionBidon
  label:
    fr: Êtes-vous pour?
  options: yesno

- type: sectionReutilisable
    - parametres:
       param1 = val('questionBidon')
       param2 = 'valeurParDefaut'
```
