### ISSUE TITLE
Ajouter la valeur d'un ou plusieurs champs du formulaire dans l'aiguillage en mode redirectionUrl

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#156]
````yaml
config:
  aiguillage:
    choix:
      - mode: redirectionUrl
        url: http://www.google.ca
````

Est-ce possible d'ajouter la valeur d'un des champs du formulaire dans l'url
par exemple : url: http://www.google.ca?noFormulaire={form_noFormulaire}

[AB#73341](https://devops700.itp.extra/700/TPM/_workitems/edit/73341)
