### ISSUE TITLE
Injecter un logo en entête de page dans le document produit par genererWord en utilisant le template par défaut

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/FRW#169]
Est-ce qu'il serait possible d'injecter une image comme un logo en entête de page en utilisant le gabarit par défaut?

avec une config du genre dans le fichier default.v0.transmission:
```
etapes:
  # Générer un document style questions/réponses à partir d'un gabarit word (gabarit par défaut)
  - tache: genererWord
    options:
      imageEntete: "data:image/gif;base64,sHfessdad=="
```

ou dans FORM.v1.bind

```
bundles:
    # le nom de sortie pour votre formulaire
  - nomSortie: REIBH_{{NoConfirmation}}.pdf
    templates:
      - template1
templates:
  - id: template1
    name: Nom inutile
    imageEntete: "data:image/gif;base64,sHfessdad=="
```
