### ISSUE TITLE
Injecter une valeur du model dans un label et dans l'aide

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/FRW#181]
**Décrivez votre besoin**
Pouvoir utiliser une valeur du model dans le libellé d''un champ

**Décrivez les alternatives que vous avez envisagées**
Utiliser un composant dynamic pour donner la précision

**Propostion de solution**
Permettre la config suivante pour les label et l'aide
```
- type: dynamic
  tag: p
  text: 
    fr: J'atteste l'abandon de mon certificat portant le numéro {{val('noCertificat')}}.
- type: radio
  name: "atestationAbandon"
  label:
    fr: J'atteste l'abandon de mon certificat portant le numéro {{val('noCertificat')}}.
  options: yesno
  help:
    fr: test {{val('noCertificat')}}
```
le résultat actuel est:
![image](https://github.com/MTESSDev/FRW/assets/112179879/b54d18d1-9bb6-4550-816c-538c7814a4ad)

AB#72841
