### ISSUE TITLE
Améliorations proposées pour la tâche envoyerCourriel

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#197]
J'ai commencé à tester la nouvelle fonctionnalité pour envoyer des courriels avec la tâche envoyerCourriel du fichier de transmission. Voici ce que je vois qui pourrait être ajouté à cette fonctionnalité pour permettre la versalité des courriels comme dans ECS25A. Le gros avantage que je vois d'utiliser cette nouvelle fonctionnalité est qu'il y a des liens vers les pièces jointes au lieu de joindre les fichiers. Cela permet d'éviter d'être confronté à une limite de poids de pièces jointes dans les courriels.

Il se pourrait que les choses ci-dessous soit déjà possibles et que je ne savais pas comment faire.

### 1 - Permettre d'insérer un courriel du formulaire dans les destinataires des courriels envoyés avec la tâche envoyerCourriel

```yaml
gabaritsCourriels:
  - id: traitementSignataire
      production:
        - '{{ donneesFormulaire.form.courrielProchaineEtape }}'
```

### 2 - Permettre le overrideAdresseA comme dans ECS25A
 
```yaml
envoyerMultipleBoiteGenerique:
    - arretSurCorrespondance: false
      actif: 'true'
      envoyerBoiteGenerique:
        - idCourriel: traitementDEC
          conditions:
            - champCalcule: "{{form_choixSecteur}}"
              condition: "=="
              valeur: "admissibiliteEncaissement"
          overrideAdresseA:
            production: boitecourriel@mess.gouv.qc.ca
```

### 3 - Ajouter des exemples d'utilisations de questionsFormulaire dans le guide
**Ajout proposé**

![image](https://github.com/MTESSDev/FRW/assets/43148349/9825c883-37af-4f69-964a-7c3825735cad)

[AB#75296](https://devops700.itp.extra/700/TPM/_workitems/edit/75296)
