### ISSUE TITLE
Est-ce qu'il y a une façon que le token ne soit pas envoyé dans le json à la soumission

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#204]
Pour un formulaire, on a ajouté un token en préremplissage dans les headers dans le data comme ceci (en php) :

$data["token"] = "abcd";
$data["urlApex"] = "https://poa....."
$data["form"]["nomDunChamp"] = "valeur préremplie";

J'utilise ensuite le token pour appeler APEX dans le fichier de transmission.
![image](https://github.com/MTESSDev/FRW/assets/43148349/f394d290-0754-40dd-b530-875a8002ccf2)

Je pensais que le token ne serait pas envoyé dans le json final puisque je ne l'ai pas prérempli dans le $data["form"] mais ce n'est pas le cas. 

![MicrosoftTeams-image](https://github.com/MTESSDev/FRW/assets/43148349/c2e15475-9933-4400-88d8-cea4f8f4907d)

[AB#76497](https://devops700.itp.extra/700/TPM/_workitems/edit/76497)

**Comment by anisite** [comment]
Salut !

s'il n'est pas trop tard tu pourrais changer ce bout de ta config:

````yaml
    content:
      json_content: |
        {
              "champsFormulaire": {{{Json DonneesFormulaire}}}
        }
````
ici tu précise au traitement de mettre toutes les "DonneesFormulaire" dans champsFormulaire, ça inclut tout tout tout le json même la partie "cachée"

pour remédier a ça tu peux changer ta config a ta guise tel que :

````yaml
    content:
      json_content: |
        {
              "champsFormulaire": {{{Json DonneesFormulaire.form}}}
        }
````
évidement, si tu dois conserver ta structure a deux niveau c'est possible avec un peu d'imagination : 
 ````yaml
    content:
      json_content: |
        {
              "champsFormulaire":  
                     { 
                        "form" : {{{Json DonneesFormulaire.form}}}
                     }
        }
````

reviens nous avec ton résultat
