### ISSUE TITLE
[ECS] Le conditionOu dans envoyerBoiteGenerique n'est pas considéré

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#215]
J'ai trouvé un problème dans avec la fonctionnalité envoyerBoiteGenerique

Ceci fonctionne

```yaml
envoyerMultipleBoiteGenerique:
    - arretSurCorrespondance: false
      actif: 'true'
      envoyerBoiteGenerique:
        - idCourriel: traitement
          conditions:
            - champCalcule: "{{form_choixSecteur}}"
              condition: "==" 
              valeur: "secteur1"
          overrideAdresseA:
            production: courriel@mess.gouv.qc.ca
```

Quand on met un conditionsOu, les conditions ne sont pas considérées et le courriel s'envoi quand même.

```yaml
envoyerMultipleBoiteGenerique:
    - arretSurCorrespondance: false
      actif: 'true'
      envoyerBoiteGenerique:
        - idCourriel: traitement
          conditionsOu:
            - champCalcule: "{{form_choixSecteur}}"
              condition: "==" 
              valeur: "secteur1"
            - champCalcule: "{{form_choixSecteur}}"
              condition: "==" 
              valeur: "secteur2"
          overrideAdresseA:
            production: courriel@mess.gouv.qc.ca
```

[AB#78342](https://devops700.itp.extra/700/TPM/_workitems/edit/78342)
