### ISSUE TITLE
[Hors FRW] Améliorations pour ECS25A

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#226]
Tel que discuté avec @anisite, voici ce qui serait fortement aidant si c'était ajouté dans les possibilités de ECS25A

- Permettre de mettre plusieurs courriels séparés par un ; dans le a, cc, cci, et aussi le overrideAdresseA si possible
- Permettre de mettre la valeur d'un champ (au lieu d'une boîte de courriel) dans le overrideAdresseA

```yaml
a:
      tous: '{{#form_groupeRepresentantsEmployeurs_0_courrielRepresentantEmployeur}}{{{.}}}{{/form_groupeRepresentantsEmployeurs_0_courrielRepresentantEmployeur}};{{#form_groupeRepresentantsEmployeurs_1_courrielRepresentantEmployeur}}{{{.}}}{{/form_groupeRepresentantsEmployeurs_1_courrielRepresentantEmployeur}}'
```

```yaml
envoyerMultipleBoiteGenerique:
  - arretSurCorrespondance: false
    actif : '{{#courrielRepresentantEmployeurActif}}true{{/courrielRepresentantEmployeurActif}}'
    envoyerBoiteGenerique:
      - idCourriel: traitementRepresentantEmployeur
        overrideAdresseA:
          tous: >-
            {{#form_groupeRepresentantsEmployeurs_0_courrielRepresentantEmployeur}}{{{.}}}{{/form_groupeRepresentantsEmployeurs_0_courrielRepresentantEmployeur}} 
            {{#form_groupeRepresentantsEmployeurs_1_courrielRepresentantEmployeur}};{{{.}}}{{/form_groupeRepresentantsEmployeurs_1_courrielRepresentantEmployeur}}
```

[AB#79604](https://devops700.itp.extra/700/TPM/_workitems/edit/79604)
