### ISSUE TITLE
documenter la config debuterFormulaire dans le P700

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#230]
exemple de TRDOC
```yaml
config:  
  debuterFormulaire:
    authentifie:
      urlAuthentification: 
          fr: "http://mondossier.mtess.gouv.qc.ca/Services?categorie=VOSDOC"
          en: "http://mondossier.mtess.gouv.qc.ca/en/Services?categorie=VOSDOC"

```

AB#73332
