### ISSUE TITLE
Validation d'un champs obligatoire affiché sur une condition dans un groupe répétable

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/FRW#247]
**Description du problème**
Dans un groupe répétable, j'ai un champ "Nom" qui s'affiche seulement si on sélectionne "Autre" dans un droplist. Il est obligatoire lorsqu'affiché. Quand le champs "Nom" n'est pas affiché, il y a un plantage dans la page de révision.

**Étapes pour reproduire le bogue**
1. Configurer une section tel que définit plus bas
2. Accéder au formulaire et naviguer à la section
3. Sélectionner une valeur dans la liste différentes de "Autre"
4. Aller à la page de révision
5. BANG!

Si vous sélectionnez la valeur "Autre" dans la liste et saisissez un "Nom" et que vous allez à la page de révisions, il n'y a pas d'erreur

**Comportement attendu**
Le champ masqué doit être ignoré et ne pas avoir de plantage dans la page de révision.

**Captures écran**
![image](https://github.com/MTESSDev/FRW/assets/112179879/903ef79d-aeb5-4220-9205-26573dac6218)
![image](https://github.com/MTESSDev/FRW/assets/112179879/79d52f3a-56d0-4114-9627-9eae45048425)
![image](https://github.com/MTESSDev/FRW/assets/112179879/9c84b264-1129-402b-af00-1023e87ab4c6)

pas d'erreur:
![image](https://github.com/MTESSDev/FRW/assets/112179879/33ac667f-5750-4d9b-827f-b5deed9eb372)

**Appareil utilisé/fureteur utilisé**
 - OS: Windows 10
 - Fureteur: Edge Version 124.0.2478.105
 
**Configuration de la section**
```yaml
#Ordre professionnel
        - section:
            fr: Ordres professionnels
            en: (eng) Ordres professionnels
          id: secOrdre
          components:
            - type: radio
              name: membreOrdre
              label:
                fr: Êtes-vous membre d'un ou de plusieurs ordres professionnels constitués conformément au Code des professions du Québec?
                en: (eng) Êtes-vous membre d'un ou de plusieurs ordres professionnels constitués conformément au Code des professions du Québec?
              options: yesno
            - type: radio
              name: eteMembreOrdre
              label:
                fr: Avez-vous été membre d'un ou de plusieurs ordres professionnels constitués conformément au Code des professions du Québec au cours des 5 dernières années? 
                en: (eng) Avez-vous été membre d'un ou de plusieurs ordres professionnels constitués conformément au Code des professions du Québec au cours des 5 dernières années?
              options: yesno
            
            - type: repeatableGroup
              name: ordres
              repeatable: true
              v-if: val('membreOrdre') === 'true' || val('eteMembreOrdre') === 'true'
              label:
                fr: Ordres professionnels
                en: Professional order
              instanceLabel:
                fr: "Ordre professionnel"
                en: Professional order
              addLabel:
                fr: Ajouter un ordre
                en: Add an order
              removeLabel:
                fr: Supprimer
                en: Remove
              components:
              - type: listeDeroulante
                name: nomOrdre
                additionals:
                  largeur: lg
                options: 
                  Ordre ingenieurs:
                    fr: Ordre des ingénieurs du Québec
                    en: (eng) Ordre des ingénieurs du Québec
                  Ordre architectes:
                    fr: Ordre des architectes du Québec
                    en: (eng) Ordre des architectes du Québec
                  Ordre technologues:
                    fr: Ordre des technologues professionnels du Québec
                    en: (eng) Ordre des technologues professionnels du Québec
                  Autre:
                    fr: Autre
                    en: (eng) Autre
              - type: text
                name: nomOrdreAutre
                label:
                  fr: "Nom"
                  en: "Name"
                v-if: val('ordres.nomOrdre', index) === 'Autre'
              - type: text
                name: numeroOrdre
                label:
                  fr: "Numéro"
                  en: (eng) Numéro
```

[AB#82606](https://devops700.itp.extra/700/TPM/_workitems/edit/82606)
