### ISSUE TITLE
La page 0 est mal exécutée sur un v-if === false sur la première section d'un formulaire. 

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/FRW#251]
**Description du problème**
Tel que discuté avec @j0ber :
Lorsque la première section du formulaire est conditionnée par un champs du modèle pré remplis et que la condition est fausse, cette section ne doit pas s'afficher. Hors, à l'ouverture du formulaire, on voit le titre de la section mais pas son contenu. Elle n'est pas dans le menu. Il semble y avoir un problème avec la navigation sur la "bonne" première page du formulaire.

Le bug arrive avec la config plus bas. Le test dans le bac à sable est trompeur à cause du focus au moment du Save.

**Étapes pour reproduire le bogue**
configurer:
```
form:
  title:
    fr: TEST X = Y
    en: (eng) Text X = Y

  sectionsGroup:
    -  sections:
        - section:
            fr: Afficher si X = Y
            en: (eng) Afficher si X = Y
          id: secXY
          v-if: val('champX') === 'y'
          components:
          - name: champX
            type: hidden
            value: 'true'
          - name: ChampQuiNeAffichePas
            type: text
            label:
              fr: Champ qui ne s'affiche pas
              en: Champ qui ne s'affiche pas
        - section:
            fr: Première section
            en: (eng) Première section
          id: secPremiere
          components:
          - name: Nom
            type: text
            label:
              fr: Nom
              en: Name
        - section: 
            fr: Révision
            en: Revision
          id: revision
          components:
            - type: dynamic
              tag: div
              v-if: val('EtatRevision') === 'sans-erreur'
              classes: texte-revision
              text: 
                fr: Vos réponses ont été validées.
                en: Your answers have been validated.
```

**Comportement attendu**
La navigation doit se faire sur la bonne section à affiche. 

**Captures écran**
![image](https://github.com/MTESSDev/FRW/assets/112179879/6decb8d6-8c00-49a5-a401-fcaecfebcceb)

**Appareil utilisé/fureteur utilisé**
 - OS: (ex: Windows 10)
 - Fureteur: (ex: Chrome 111)
