### ISSUE TITLE
Erreur avec une adresse dans un groupe

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/FRW#273]
**Description du problème**
J'utilise un formulaire d'aiguillage avec un courriel de reprise pour forcer la validation de l'adresse Courriel et la saisie des informations du demandeur. Si je met une adresse International dans le formulaire, ça ne fonctionne pas.

**Étapes pour reproduire le bogue**
1. Configurer un formulaire d'aiguillage avec une configuration semblable:
```
- type: group
  name: informationDemandeur
  components:
  - name: salutation
    type: radio
    label:
      fr: Salutation
      en: (eng) Salutation
    options:
      Mr.:
        fr: Monsieur
        en: (eng) Monsieur
      Mrs.:
        fr: Madame
        en: (eng) Madame

  - name: nom
    type: text
    label:
      fr: Nom
      en: Name
  - name: prenom
    type: text
    label:
      fr: Prénom
      en: First name
  - name: dateNaissance
    type: date
    label:
      fr: Date de naissance
      en: Date of birth
    validations:
      before:

  - name: adresseDomicile
    label:
      fr: Adresse de votre domicile
      en: (eng) Adresse de votre domicile
    type: adresseInternationale
    additionals:
      conserver-donnees-postes-canada: true

  - type: inline
    classes: no-wrap
    components:
    - type: tel
      name: telephone
      label:
        fr: Téléphone
        en: Phone number
      outerClasses: md

  - type: tel
    name: autreTelephone
    label:
      fr: Cellulaire
      en: (eng) Cellulaire
    outerClasses: md
    validations:
      optional: null
  - name: courriel
    type: email
    label:
      fr: Courriel
      en: Email address
    help :
      fr: Un message de validation vous sera envoyé à cette adresse courriel. Veuillez verifier vos indésirables si vous n'avez rien reçu.
      en: (eng) Un message de validation vous sera envoyé à cette adresse courriel. Veuillez verifier vos indésirables si vous n'avez rien reçu.
    validations:
      max: 60,length
  - name: courrielConfirmation
    type: email
    label:
      fr: Courriel (confirmation)
      en: Email address (confirmation)
    validations:
      confirm: courriel
- type: password
  name: MDPAConfirmer
  label: 
      fr: Mot de passe
      en: (EN)Confirmer le mot de passe
- type: password
  name: MDPConfirmation
  label: 
      fr: Mot de passe (confirmation)
      en: (EN)Confirmer le mot de passe
  validations:
      confirm: MDPAConfirmer 
```

2. Dans la page Révision, cliquer sur "Poursuivre votre demande" (Soumettre)
3. BANG! Rien ne se passe. I n'y a pas de message d'erreur dans la console du navigateur
4. Retirer l'adresse `- name: adresseDomicile` de la configuration
5. ça fonctionne et le courriel de reprise est envoyé.

**Comportement attendu**
La présence d'un bloc adresse dans le formulaire d'aiguillage ne cause pas de problème.

**Date de l'erreur**
2024-06-21 15:18
Dans l'environnement IT

[AB#84494](https://devops700.itp.extra/700/TPM/_workitems/edit/84494)
