### ISSUE TITLE
Ajouter Content-Type sur les headers d'exemples dans les transmissions

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#291]
Bonifier la doc à quelques places (exemples) pour ajouter ``Content-Type: application/json; charset=utf-8`` sur les transmissions comme ça :

````yaml
http_client:
  appel_externe:
      method: POST
      url: [URL]
      headers:
          Accept: application/json
          Content-Type: application/json; charset=utf-8
````

[AB#90484](https://devops700.itp.extra/700/TPM/_workitems/edit/90484)
