### ISSUE TITLE
Bloc adresse dans un repeatableGroup

### ISSUE THREAD

**Issue by FrancisLac** [MTESSDev/FRW#316]
**Description du problème**
Je veux réaliser un bloc répétable et y incruster un bloc adresse. Mon problème est que le premier bloc fonctionne, mais si j'ajoute une nouvelle adresse je ne peux plus aller modifier la première vu que le bloc adresse devient un bloc en gris avec aucun champ. Dans l'environnement bac-à-sable.

**Comportement attendu**
Ajouter des adresses et retourner dans celle qui on été créer pour les modifier

**Captures écran**

![Image](https://github.com/user-attachments/assets/a880cdec-d026-416f-9d66-0fb7072155a2)

**Appareil utilisé/fureteur utilisé**
 - OS: Windows 10
 - Fureteur: Chrome

[AB#97886](https://devops700.itp.extra/700/TPM/_workitems/edit/97886)

**Comment by j0ber** [comment]
Bonjour,

Pourriez-vous fournir votre section de fichier de configuration contenant la section répétable s.v.p. ?

**Comment by FrancisLac** [comment]
Bonjour, 

Voici le code de la section répétable

```
 - section:
          fr: Adresse du bâtiment
        id: section4
        v-if: val('InstallationMemeAdresse') === 'false'
        components:
        - type: repeatableGroup
          name: repeatableGroup1
          label:
            fr: Adresse de l'installation
          addLabel:
            fr: Ajouter une adresse
          removeLabel:
            fr: Supprimer
          repeatable: true
          components:
            - type: adresse
              name: AdresseInstallation
```
