### ISSUE TITLE
Groupe répétable - demande de confirmation avant suppression

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/FRW#335]
#332 
Bonjour

Est-ce qu'il est possible d'ajouter une message de confirmation "Voulez-vous vraiment supprimer le Groupe {Numéro du groupe}?" sur le bouton 

du genre: 

```
- type: repeatableGroup
        name: repeatableGroup2
        repeatable: true
        label:
          fr: Exemple de groupe répétable
        instanceLabel:
          fr: Groupe répétable
        addLabel:
          fr: Ajouter un groupe
        removeLabel:
          fr: Supprimer ce groupe
```
```
        removeConfirmation:
          fr: Voulez-vous vraiment supprimer le {instanceLabel} {Numéro du groupe}?
```
