### ISSUE TITLE
Domaines de valeurs conditionnels dans un groupe répétable

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/FRW#344]
Bonjour

Dans un groupe répétable, nous avons le domaine de valeur "Nature des travaux" qui doit être conditionné par la sélection du "Type de travaux". 

![Image](https://github.com/user-attachments/assets/d6ae5199-d545-4cf0-bc91-45cde2f75ff8)

Nous utilisons le script suivant.

```
  domaines:
    NaturesTravaux:
        AmenagementPaysage:
            label:
                fr: Aménagement paysagé
                en: (eng) Aménagement paysagé
            v-if: this.val('travaux.typeTravaux') === 'Amenagement Exterieur'
        AgrandissementBatiment:
            label:
                fr: Agrandissement de bâtiment
                en: (eng) Agrandissement de bâtiment
            v-if: this.val('travaux.typeTravaux') === 'RenovationAgrandissement'
```

Ce code fonctionne pour le 1er groupe. Mais dans le 2e, la liste de "Nature des travaux" reste toujours la même conditionnée sur le choix du "Type de travaux" du 1er groupe.

Je sais qu'on doit utiliser "index" quelque part. Nous avons essayé :

` v-if: this.val('travaux.typeTravaux', index) === 'Amenagement Exterieur'`

Mais nous obtenons cette erreur au runtime :

![Image](https://github.com/user-attachments/assets/0d4998b8-6b59-40c4-919f-468639a4919b)

Comment est-ce que nous pouvons conditionner la liste "Nature des travaux" de chaque groupe en fonction de la sélection du "Type de travaux" du groupe courant?

Merci

[AB#105942](https://devops700.itp.extra/700/TPM/_workitems/edit/105942)
