### ISSUE TITLE
Limiter l'affichage du formulaire dans une seule langue 

### ISSUE THREAD

**Issue by MpmMtess** [MTESSDev/FRW#7]
Comment faire pour enlever le English en haut du formulaire afin d’avoir seulement la langue française?

**Comment by anisite** [comment]
Bonjour, normalement l'information aurait du être dans le P700U je vais faire corriger rapidement le tout.

dans le bloc config du formulaire (à ajouter au même niveau que `form:`) il faut ajouter la propriétée `formulaireUnilingue: true`

tel que :

```yaml
config:
    formulaireUnilingue: true
    
form:
    [....]
```
